name: Kilroy
options:
  bundleIdPrefix: com.loudlabs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    ENABLE_PREVIEWS: YES

targets:
  Kilroy:
    type: application
    platform: iOS
    sources:
      - path: Kilroy
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.loudlabs.kilroy
        INFOPLIST_FILE: Kilroy/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
    info:
      path: Kilroy/Resources/Info.plist
      properties:
        CFBundleName: Kilroy
        CFBundleDisplayName: Kilroy
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        CFBundlePackageType: APPL
        CFBundleExecutable: Kilroy
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: true
        NSLocationWhenInUseUsageDescription: "Kilroy uses your location to surface memories at the places you took them."
        NSLocationAlwaysAndWhenInUseUsageDescription: "Kilroy uses your location in the background to notify you when you're near a memory."
        NSPhotoLibraryUsageDescription: "Kilroy scans your photo library to find geotagged memories and surface them at the right places."
        NSCameraUsageDescription: "Kilroy uses your camera to capture new memories."
        NSMicrophoneUsageDescription: "Kilroy uses your microphone to record video memories."
